// Author: Alec Brothwood (23076824) - Project Manager
// Author: Douaa Tadli (23012698) - Backend Developer
// File: pdf_export_service.dart
// Purpose: Generate invoice/receipt PDFs and preview them.

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/invoice_model.dart';
import '../models/tenant_model.dart';
import '../models/apartment_model.dart';
import '../models/lease_model.dart';
import '../models/payment_model.dart';

class PdfExportService {
  static final _currency = NumberFormat.currency(locale: 'en_GB', symbol: '£');
  static final _dateFmt = DateFormat('dd MMM yyyy');

  Future<void> previewInvoice({
    required InvoiceModel invoice,
    required TenantModel tenant,
    required LeaseModel lease,
    required ApartmentModel apartment,
    List<PaymentModel> payments = const [],
  }) async {
    final theme = await _theme();
    final doc = pw.Document(theme: theme);
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          _header('PARAGON APARTMENT MANAGEMENT', 'INVOICE'),
          pw.SizedBox(height: 20),
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Expanded(child: _kv('Invoice #', invoice.invoiceNumber)),
              pw.Expanded(
                  child: _kv('Issue date', _dateFmt.format(invoice.issueDate))),
              pw.Expanded(
                  child: _kv('Due date', _dateFmt.format(invoice.dueDate))),
            ],
          ),
          pw.SizedBox(height: 16),
          pw.Text('Billed to', style: _bold(12)),
          pw.Text(tenant.fullName),
          pw.Text(tenant.email),
          pw.Text(tenant.phone),
          pw.SizedBox(height: 12),
          pw.Text('Property', style: _bold(12)),
          pw.Text(
              '${apartment.apartmentNumber}, ${apartment.location}, ${apartment.city}'),
          pw.Text(apartment.type),
          pw.SizedBox(height: 16),
          _table(
            headers: ['Description', 'Period', 'Amount'],
            rows: [
              [
                'Monthly rent – ${apartment.apartmentNumber}',
                invoice.periodLabel,
                _currency.format(invoice.amount),
              ],
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              'Total due: ${_currency.format(invoice.amount)}',
              style: _bold(14),
            ),
          ),
          if (payments.isNotEmpty) ...[
            pw.SizedBox(height: 24),
            pw.Text('Payments applied', style: _bold(12)),
            _table(
              headers: ['Date', 'Method', 'Reference', 'Amount'],
              rows: payments
                  .map((p) => [
                        _dateFmt.format(p.paymentDate),
                        p.method.name,
                        p.referenceNumber ?? '-',
                        _currency.format(p.amount),
                      ])
                  .toList(),
            ),
          ],
          pw.SizedBox(height: 24),
          pw.Text(
            'Status: ${invoice.status.name.toUpperCase()}',
            style: _bold(12),
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'This invoice is generated by the PAMS demonstration system. '
            'No payment processing is performed; records are retained for '
            'accounting emulation only.',
            style: pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey600,
              fontStyle: pw.FontStyle.italic,
            ),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(onLayout: (_) async => doc.save());
  }

  Future<void> previewReceipt({
    required PaymentModel payment,
    required TenantModel tenant,
    required ApartmentModel apartment,
  }) async {
    final theme = await _theme();
    final doc = pw.Document(theme: theme);
    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (_) => pw.Padding(
          padding: const pw.EdgeInsets.all(32),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _header('PARAGON APARTMENT MANAGEMENT', 'PAYMENT RECEIPT'),
              pw.SizedBox(height: 24),
              _kv('Receipt ref', payment.referenceNumber ?? payment.id),
              _kv('Date', _dateFmt.format(payment.paymentDate)),
              _kv('Tenant', tenant.fullName),
              _kv('Apartment',
                  '${apartment.apartmentNumber}, ${apartment.location}, ${apartment.city}'),
              _kv('Method', payment.method.name),
              _kv('Amount', _currency.format(payment.amount)),
              pw.SizedBox(height: 32),
              pw.Text('Thank you for your payment.',
                  style: pw.TextStyle(fontStyle: pw.FontStyle.italic)),
            ],
          ),
        ),
      ),
    );
    await Printing.layoutPdf(onLayout: (_) async => doc.save());
  }

  // -------------------------------------------------------- PDF helpers

  pw.Widget _header(String company, String title) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(company,
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blue800,
              )),
          pw.Text(title, style: _bold(14)),
          pw.Divider(color: PdfColors.grey500),
        ],
      );

  pw.Widget _kv(String k, String v) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 2),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(k,
                style: pw.TextStyle(
                    color: PdfColors.grey700, fontSize: 10)),
            pw.Text(v, style: _bold(11)),
          ],
        ),
      );

  Future<pw.ThemeData> _theme() async {
    final base = await PdfGoogleFonts.notoSansRegular();
    final bold = await PdfGoogleFonts.notoSansBold();
    final italic = await PdfGoogleFonts.notoSansItalic();
    final boldItalic = await PdfGoogleFonts.notoSansBoldItalic();
    return pw.ThemeData.withFont(
      base: base,
      bold: bold,
      italic: italic,
      boldItalic: boldItalic,
    );
  }

  pw.Widget _table({
    required List<String> headers,
    required List<List<String>> rows,
  }) =>
      pw.Table.fromTextArray(
        headers: headers,
        data: rows,
        headerStyle: pw.TextStyle(
          color: PdfColors.white,
          fontWeight: pw.FontWeight.bold,
        ),
        headerDecoration: const pw.BoxDecoration(color: PdfColors.blue700),
        cellAlignment: pw.Alignment.centerLeft,
        cellStyle: const pw.TextStyle(fontSize: 11),
        border: pw.TableBorder.all(color: PdfColors.grey300),
      );

  pw.TextStyle _bold(double size) => pw.TextStyle(
        fontSize: size,
        fontWeight: pw.FontWeight.bold,
      );
}
